const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('lumi', {
  start:                 ()       => ipcRenderer.send('start'),
  stop:                  ()       => ipcRenderer.send('stop'),
  restart:               ()       => ipcRenderer.send('restart'),
  startBB:               ()       => ipcRenderer.send('start-bb'),
  stopBB:                ()       => ipcRenderer.send('stop-bb'),
  openBrowser:           ()       => ipcRenderer.send('open-browser'),
  openBBBrowser:         ()       => ipcRenderer.send('open-bb-browser'),
  clearLogs:             ()       => ipcRenderer.send('clear-logs'),
  getConfig:             ()       => ipcRenderer.invoke('get-config'),
  saveConfig:            (cfg)    => ipcRenderer.send('save-config', cfg),
  isRunning:             ()       => ipcRenderer.invoke('is-running'),
  isBBRunning:           ()       => ipcRenderer.invoke('is-bb-running'),
  isSetupComplete:       ()       => ipcRenderer.invoke('is-setup-complete'),
  updateLumiverse:       (branch) => ipcRenderer.send('update-lumiverse', branch),
  checkLauncherUpdate:   ()       => ipcRenderer.send('check-launcher-update'),
  installLauncherUpdate: ()       => ipcRenderer.send('install-launcher-update'),
  resetSetup:            ()       => ipcRenderer.send('reset-setup'),
  getVersion:             ()       => ipcRenderer.invoke('get-version'),
  minimize:              ()       => ipcRenderer.send('window-minimize'),
  hide:                  ()       => ipcRenderer.send('window-hide'),
  termInput:             (data)   => ipcRenderer.send('term-input', data),
  termResize:            (c, r)   => ipcRenderer.send('term-resize', { cols: c, rows: r }),

  onLog:          (cb) => ipcRenderer.on('log',           (_, d) => cb(d)),
  onStatus:       (cb) => ipcRenderer.on('status',        (_, d) => cb(d)),
  onBBStatus:     (cb) => ipcRenderer.on('bb-status',     (_, d) => cb(d)),
  onClearLogs:    (cb) => ipcRenderer.on('clear-logs',    ()     => cb()),
  onUpdateStatus: (cb) => ipcRenderer.on('update-status', (_, d) => cb(d)),
  onTermData:     (cb) => ipcRenderer.on('term-data',     (_, d) => cb(d)),
  onMode:         (cb) => ipcRenderer.on('mode',          (_, d) => cb(d)),
});
